name: Create a comment on issue

on:
  issues:
    types: [opened]

jobs:
  comment-on-issue-with-github-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
