name: Create a comment on issue

on:
  issues:
    types: [opened]

# Add this permissions block
# permissions:
#   issues: write

jobs:
  # using github community action 'create-or-update-comment'
  comment-with-action:  
    runs-on: ubuntu-latest
    # The permissions block gives the job write access to issues, which is necessary for creating comments.
    permissions: 
      issues: write  
    steps:
      # This step dumps the GitHub context (event information) as JSON and pipes it through jq for pretty-printing. This is useful for debugging and seeing what information is available in the github.event object.
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq  
        shell: bash
      # This step uses the peter-evans/create-or-update-comment@v4 action to create a comment on the issue. It specifies:
      # The issue number (taken from the event context)
      # The body of the comment (using Markdown formatting)
      # A '+1' reaction to be added to the comment
      - name: Create comment using github-community(action-create-or-update-comment)
        uses: peter-evans/create-or-update-comment@v4  
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'
  
  comment-with-github-api:
    runs-on: ubuntu-latest
    # The permissions block gives the job write access to issues, which is necessary for creating comments.
    permissions: 
      issues: write  
    steps:
      - name: Create comment using github api
        run: |
          # GitHub CLI api
          # https://cli.github.com/manual/gh_api

          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${OWNER}/${REPO}/issues/${ISSUE_NUMBER}/comments
            -f "body= Commenting using github api"
        env:
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}