name: Create a comment on issue

on:
  issues:
    types: [opened]

# Add this permissions block
# permissions:
#   issues: write

jobs:
  comment-on-issue-with-github-action:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'